Algoritmo "Variáveis"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cleison Melo
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : José Humberto dos Santos júnior
// Data atual  : 27/10/2023
Var
// Seção de Declarações das variáveis 
    nota: inteiro, nota2: real, nome: caractere, passou: logico;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo